services:
  web:
    build: ./php
    volumes:
      - ./php:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  nginx:
    image: nginx:1.28.0
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: mariadb:12.0.2
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ~/goinfre/data:/var/lib/mysql
